{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "woo-hoo.fullname" . }}
  labels:
    {{- include "woo-hoo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.openrouterApiKey }}
  OPENROUTER_API_KEY: {{ .Values.config.openrouterApiKey | quote }}
  {{- end }}
  {{- if .Values.config.gppApiToken }}
  GPP_API_TOKEN: {{ .Values.config.gppApiToken | quote }}
  {{- end }}
{{- end }}
